server:
  port: 8084  # ✅ Different port

spring:
  application:
    name: emergency-service  # 
    
  datasource:
    url: jdbc:h2:mem:emergencydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

debug: true      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint: 
    health:
      show-details: always          
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
     prefer-ip-address: true  
    
    
    
   

  
    

     

     
  
