server:
  port: 8761
spring:
  application:
    name: discovery-server
  
logging:
  level:
    root: DEBUG
eureka:
  instance:
    hostname: localhost
    
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka/
