server:
  port: 8082  # ✅ Different port

spring:
  application:
    name: waste-service  # ✅ Correct name
management:
  endpoints:
    web:
      exposure:
        include: "*"    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
